algoritmo "N_essimoNumeroPares"
// Função :
// Autor :
// Data : 05/07/2019
// Encontre todos os numeors pares de 1 até o n-éssimo número
var
         numeroLimite, numero: inteiro
inicio
         escreva("Informe o n-éssimo número: ")
         leia(numeroLimite)
         
         para numero de 1 ate numeroLimite faca
              se(numero mod 2 = 0) entao
                        escreval(" Esse numero é par: ", numero)
              fimse
         fimpara
         
fimalgoritmo
